### ISSUE TITLE
hello，would you please give a link for downloading the mini-Imagenet datasets? I can't download with google. Thank you!

### ISSUE THREAD

**Issue by lyxdlut** [iCVTEAM/Dara#1]

**Comment by longspringcity** [comment]
Hi, you can download it  at the following link and organize into a proper file structure：

https://www.kaggle.com/datasets/arjunashok33/miniimagenet/data

or

https://www.kaggle.com/datasets/zcyzhchyu/mini-imagenet

We still recommend to download from the link given in the .readme to avoid additional operations.

Have a nice day!
